CREATE OR REPLACE VIEW `MAPP_V_EIH_LEAPFROG_CNSTL` AS
SELECT  
	trans.EXTERNAL_ID AS 'FCPA_PROJ_ID'
	, att.HCP_ID AS 'FCPA_PROJ_AND_LN'
	, vend.NAME AS 'TRANS_PTY_VNDR_NAME'
	, CASE 
		WHEN att.VENDOR_ID IS NULL THEN att.NEW_VENDOR_NAME 
	END AS 'VNA_VNDR_NM'
	, att.FIRST_NAME AS 'CNSLT_FST_NM'
	, att.LAST_NAME AS 'CNSLT_LST_NM'
	, att.AFFILIATIONS AS 'EMPLR'
	, att.ROLE AS 'POSN'
	, cntry.NAME AS 'CNTRY_OF_RES'
	, CASE WHEN att.HCP_ID IS NULL THEN 
		CASE WHEN att.GO_STATUS = 'GO' THEN 'GO-NoN HCP'
		ELSE 'NoN HCP-NoN GO'
		END
	ELSE 
		CASE WHEN att.GO_STATUS = 'GO' THEN 'HCP-GO'
		ELSE 'HCP-NoN GO'
		END
	END AS 'GO_STAT'
	, CASE WHEN att.NIP_PIGO_STATUS = 'NIPPIGO' THEN 1 ELSE 0 END AS 'NIP_PIGO_CHK_BOX'
	, CASE 
		WHEN att.PIGO_STATUS = 'PIGO' THEN 'PIGO'
		WHEN att.PIGO_STATUS = 'NPIGO' THEN 'Non PIGO'
		ELSE 'PIGO Unknown'
	END AS 'PIGO_STAT_BASED_ON'
	, att.PIGO_STATUS AS 'PIGO_STAT'
	, CASE 
		WHEN att.PIGO_STATUS = 'PIGO' THEN att.PRIMARY_PIGO_RATIONALE
	END AS 'PIGO_RTNL'
	, CASE 
		WHEN att.PIGO_STATUS = 'PIGO' THEN att.PRIMARY_PIGO_RATIONALE
	END AS 'BASIS_FOR_PIGO_STAT'
	, CASE WHEN att.FMV_AMOUNT IS NOT NULL THEN 'Yes' ELSE 'Exception to FMV' END AS 'FMV_RTE_USED'
	, GROUP_CONCAT(distinct serviceData.ENG_LABEL separator ' | ') AS 'CNSLT_TYP'
	, att.FMV_AMOUNT  AS 'TRANS_AMT'
	, trans.R_CURRENCY_ISO_CD AS 'TRANS_CURR'
	, '' AS 'VND_TYP'
	, CASE
		WHEN projectOwner.COUNTRY = 'VE' THEN 'E1'
		ELSE 'SAP'
	END AS 'PFE_ERP'
	, att.SIX_MO_DECISION AS 'PIGO_DECISION'
	, trans.MODIFIED_DATETIME AS 'LST_MOD'
FROM MAPP_TRANSACTION trans
JOIN MAPP_TYPE tType ON tType.TRANSACTION_ID = trans.ID
	AND tType.R_TYPE_ID = 2
JOIN MAPP_TRANSACTION_HISTORY tHist ON tHist.TRANSACTION_ID = trans.ID
	AND tHist.ACTION_ID = 920
	AND tHist.CREATED_DATETIME >= date_format(CURRENT_DATE - interval 1 month,'%Y-%m-01 00:00:00') 
	AND tHist.CREATED_DATETIME <= date_format(last_day(CURRENT_DATE-interval 1 month),'%Y-%m-%d 23:59:59')
JOIN MAPP_REVIEW rvw ON rvw.TRANSACTION_ID = trans.ID
JOIN MAPP_REVIEW_ATTENDEES revAtt ON revAtt.REVIEW_ID = rvw.ID	
	AND revAtt.IS_REJECTED = 0
JOIN MAPP_ATTENDEES att ON att.ID = revAtt.ATTENDEE_ID
LEFT JOIN MAPP_VENDOR vend ON att.VENDOR_ID = vend.ID
LEFT JOIN MAPP_USER projectOwner ON projectOwner.ID = CASE WHEN trans.INITIATING_USER_ID IS NULL THEN trans.ON_BEHALF_OF_USER_ID ELSE trans.INITIATING_USER_ID END
LEFT JOIN MAPP_CONSULTANCY consltcy ON consltcy.TRANSACTION_ID = trans.ID
LEFT JOIN MAPP_L_CON_SERVICE lConsltcy ON lConsltcy.CONSULTANCY_ID = consltcy.ID
LEFT JOIN MAPP_R_DATA serviceData ON serviceData.ID = lConsltcy.SERVICE_ID
LEFT JOIN MAPP_R_COUNTRY cntry ON cntry.COUNTRY_CD = att.COUNTRY_CD
WHERE att.R_ATTENDEE_TYPE_ID = 200
GROUP BY trans.ID, att.ID