CREATE OR REPLACE VIEW `MAPP_V_EIH_LEAPFROG_ATTND` AS
SELECT * FROM (
	SELECT  
		trans.EXTERNAL_ID AS 'FCPA_PROJ_ID'
		, att.LAST_NAME AS 'LST_NM'
		, CASE
			WHEN FIND_IN_SET('2', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 THEN att.FIRST_NAME 
		END AS 'FST_NM'
		, CASE
			WHEN FIND_IN_SET('2', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 THEN cntry.NAME
		END AS 'CNTRY_OF_RES'
		, CASE
			WHEN FIND_IN_SET('2', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 THEN att.AFFILIATIONS 
		END AS 'EMPLR'
		, CASE
			WHEN FIND_IN_SET('2', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 THEN att.ROLE 
		END AS 'POSN'
		, CASE
			WHEN FIND_IN_SET('2', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 THEN 
				CASE WHEN att.HCP_ID IS NULL THEN 
					CASE WHEN att.GO_STATUS = 'GO' THEN 'GO-NoN HCP'
					ELSE 'NoN HCP-NoN GO'
					END
				ELSE 
					CASE WHEN att.GO_STATUS = 'GO' THEN 'HCP-GO'
					ELSE 'HCP-NoN GO'
					END
				END
		END AS 'GO_STAT'
		, CASE
			WHEN FIND_IN_SET('2', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 THEN 
				CASE 
					WHEN att.R_ATTENDEE_TYPE_ID = 202 THEN 'Requestor'
					WHEN att.R_ATTENDEE_TYPE_ID = 203 THEN 'Beneficiary'
					WHEN att.R_ATTENDEE_TYPE_ID = 204 THEN 'Controller'
				END
		END AS 'ROLE'
		, CASE
			WHEN FIND_IN_SET('2', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 THEN 
			CASE 
				WHEN att.PIGO_STATUS = 'PIGO' THEN 1 ELSE 0
			END
		END AS 'IS_PIGO'
		, CASE
			WHEN FIND_IN_SET('2', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 THEN att.HCP_ID
		END AS 'HCP_ID'
		, CASE
			WHEN FIND_IN_SET('1', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 THEN att.INTERNATIONAL_OR_DOMESTIC 
		END AS 'ATTND_TYP'
		, CASE
			WHEN FIND_IN_SET('1', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 THEN 
			CASE 
				WHEN att.PIGO_STATUS = 'PIGO' THEN 'PIGO'
				WHEN att.PIGO_STATUS = 'NPIGO' THEN 'Non PIGO'
				ELSE 'PIGO Unknown'
			END
		END AS 'PIGO_RVW'
		, CASE
			WHEN FIND_IN_SET('1', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 AND att.PIGO_STATUS = 'PIGO' THEN att.PRIMARY_PIGO_RATIONALE 
		END AS 'BASIS_FOR_PIGO_STAT'
	FROM MAPP_TRANSACTION trans
	JOIN MAPP_TYPE tType ON tType.TRANSACTION_ID = trans.ID
	JOIN MAPP_TRANSACTION_HISTORY tHist ON tHist.TRANSACTION_ID = trans.ID
		AND tHist.ACTION_ID = 920
		AND tHist.CREATED_DATETIME >= date_format(CURRENT_DATE - interval 1 month,'%Y-%m-01 00:00:00') 
		AND tHist.CREATED_DATETIME <= date_format(last_day(CURRENT_DATE-interval 1 month),'%Y-%m-%d 23:59:59')
	JOIN MAPP_REVIEW rvw ON rvw.TRANSACTION_ID = trans.ID
	JOIN MAPP_REVIEW_ATTENDEES revAtt ON revAtt.REVIEW_ID = rvw.ID	
		AND revAtt.IS_REJECTED = 0
	JOIN MAPP_ATTENDEES att ON att.ID = revAtt.ATTENDEE_ID
	JOIN MAPP_R_COUNTRY cntry ON cntry.COUNTRY_CD = att.COUNTRY_CD
	WHERE att.R_ATTENDEE_TYPE_ID <> 200
	GROUP BY trans.ID, att.ID
	UNION
	SELECT  
		trans.EXTERNAL_ID AS 'FCPA_PROJ_ID'
		, rbcs.LAST_NAME AS 'LST_NM'
		, CASE
			WHEN FIND_IN_SET('2', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 THEN rbcs.FIRST_NAME 
		END AS 'FST_NM'
		, CASE
			WHEN FIND_IN_SET('2', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 THEN cntry.NAME
		END AS 'CNTRY_OF_RES'
		, CASE
			WHEN FIND_IN_SET('2', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 THEN rbcs.RECIP_EMPLOY 
		END AS 'EMPLR'
		, CASE
			WHEN FIND_IN_SET('2', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 THEN rbcs.RECIP_EMPLOY_POSITION 
		END AS 'POSN'
		, CASE
			WHEN FIND_IN_SET('2', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 THEN 
				CASE WHEN rbcs.HCP_ID IS NULL THEN 
					CASE WHEN rbcs.GO_STATUS = 'GO' THEN 'GO-NoN HCP'
					ELSE 'NoN HCP-NoN GO'
					END
				ELSE 
					CASE WHEN rbcs.GO_STATUS = 'GO' THEN 'HCP-GO'
					ELSE 'HCP-NoN GO'
					END
				END
		END AS 'GO_STAT'
		, CASE
			WHEN 
				FIND_IN_SET('3', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 OR
				FIND_IN_SET('4', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 OR
				FIND_IN_SET('5', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 OR
				FIND_IN_SET('6', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 OR
				FIND_IN_SET('7', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 
			THEN 
				CASE 
					WHEN rbcs.R_ATTENDEE_TYPE_ID = 202 THEN 'Requestor'
					WHEN rbcs.R_ATTENDEE_TYPE_ID = 203 THEN 'Beneficiary'
					WHEN rbcs.R_ATTENDEE_TYPE_ID = 204 THEN 'Controller'
				END
		END AS 'ROLE'
		, CASE
			WHEN FIND_IN_SET('2', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 THEN 
			CASE 
				WHEN rbcs.PIGO_STATUS = 'PIGO' THEN 1 ELSE 0
			END
		END AS 'IS_PIGO'
		, CASE
			WHEN FIND_IN_SET('2', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 THEN rbcs.HCP_ID
		END AS 'HCP_ID'
		, CASE
			WHEN FIND_IN_SET('1', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 THEN ''
		END AS 'ATTND_TYP'
		, CASE
			WHEN FIND_IN_SET('1', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 THEN 
			CASE 
				WHEN rbcs.PIGO_STATUS = 'PIGO' THEN 'PIGO'
				WHEN rbcs.PIGO_STATUS = 'NPIGO' THEN 'Non PIGO'
				ELSE 'PIGO Unknown'
			END
		END AS 'PIGO_RVW'
		, CASE
			WHEN FIND_IN_SET('1', GROUP_CONCAT(tType.R_TYPE_ID COLLATE utf8mb4_general_ci))>0 AND rbcs.PIGO_STATUS = 'PIGO' THEN '' 
		END AS 'BASIS_FOR_PIGO_STAT'
	FROM MAPP_TRANSACTION trans
	JOIN MAPP_TYPE tType ON tType.TRANSACTION_ID = trans.ID
	JOIN MAPP_TRANSACTION_HISTORY tHist ON tHist.TRANSACTION_ID = trans.ID
		AND tHist.ACTION_ID = 920
		AND tHist.CREATED_DATETIME >= date_format(CURRENT_DATE - interval 1 month,'%Y-%m-01 00:00:00') 
		AND tHist.CREATED_DATETIME <= date_format(last_day(CURRENT_DATE-interval 1 month),'%Y-%m-%d 23:59:59')
	JOIN MAPP_REVIEW rvw ON rvw.TRANSACTION_ID = trans.ID
	JOIN MAPP_REVIEW_RBCS revRBCs ON revRBCs.REVIEW_ID = rvw.ID	
		AND revRBCs.IS_REJECTED = 0
	JOIN MAPP_EXTERNAL_RBCS rbcs ON rbcs.ID = revRBCs.RBC_ID
	JOIN MAPP_R_COUNTRY cntry ON cntry.COUNTRY_CD = rbcs.COUNTRY_CD
	GROUP BY trans.ID, rbcs.ID
) AS unionedTbls
ORDER BY unionedTbls.FCPA_PROJ_ID